// Generated by https://quicktype.io
// Se genera haciendo Ctrl + p -> Paste JSON as Code -> Vas avanzando

export interface ReqResList {
	page: number;
	per_page: number;
	total: number;
	total_pages: number;
	data: User[];
	support: Support;
}

export interface User {
	id: number;
	email: string;
	first_name: string;
	last_name: string;
	avatar: string;
}

export interface Support {
	url: string;
	text: string;
}
